import './listtile_module.dart';

List<ListTilemodule> physicspdf = [
  ListTilemodule(Title: 'Physical Quantites', num: 1),
  ListTilemodule(Title: 'Kinematics', num: 2),
  ListTilemodule(Title: 'Dynamics', num: 3),
  ListTilemodule(Title: 'Force, Density and Pressure', num: 4),
  ListTilemodule(Title: 'Work, Energy and Power', num: 5),
  ListTilemodule(Title: 'Deformation of Solids', num: 6),
  ListTilemodule(Title: 'Waves', num: 7),
  ListTilemodule(Title: 'Superposition', num: 8),
  ListTilemodule(Title: 'Electricity', num: 9),
  ListTilemodule(Title: 'Momentum', num: 10),
  ListTilemodule(Title: 'Moment', num: 11),
  ListTilemodule(Title: 'Particle Physics', num: 12),
  ListTilemodule(Title: 'Circular Motion', num: 13),
  ListTilemodule(Title: 'Electric Fields', num: 14),
  ListTilemodule(Title: 'Gravitation', num: 15),
  ListTilemodule(Title: 'Ideal Gases', num: 16),
  ListTilemodule(Title: 'Capacitance', num: 17),
  ListTilemodule(Title: 'Temperature', num: 18),
  ListTilemodule(Title: 'Oscillation', num: 19),
  ListTilemodule(Title: 'Magnetic Fields', num: 20),
  ListTilemodule(Title: 'Alternating Current', num: 21),
  ListTilemodule(Title: 'Nuclear Radiation', num: 22),
  ListTilemodule(Title: 'Quantam Physics and Space', num: 23),
];

List<ListTilemodule> mathpdf = [
  ListTilemodule(Title: 'Pure Mathematics 1.1', num: 1),
  ListTilemodule(Title: 'Pure Mathematics 1.2', num: 2),
  ListTilemodule(Title: 'Pure Mathematics 1.3', num: 3),
  ListTilemodule(Title: 'Pure Mathematics 3', num: 4),
  ListTilemodule(Title: 'Mechanics 1.1', num: 5),
  ListTilemodule(Title: 'Mechanics 1.2', num: 6),
  ListTilemodule(Title: 'Mechanics 1.3', num: 7),
  ListTilemodule(Title: 'Mechanics 1.4', num: 8),
  ListTilemodule(Title: 'Statistics 1.1', num: 9),
  ListTilemodule(Title: 'Statistics 1.2', num: 10),
  ListTilemodule(Title: 'Statistics 1.3', num: 11),
];
